apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-frontend
  template:
    metadata:
      labels:
        app: express-frontend
    spec:
      containers:
      - name: express-frontend
        image: express-frontend:1.0
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://flask-backend:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: express-frontend
spec:
  selector:
    app: express-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
